name: Check Chrome Webstore Version

on:
  schedule:
    - cron: '*/10 * * * *' 
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install axios cheerio puppeteer


      - name: Run script
        run: node check-webstore-version.js

      - name: Commit & Push if Changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add version.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update version.json from webstore"
          git push
